"""empty message

Revision ID: 481aa2f89d8e
Revises: 5b0c39a9c121
Create Date: 2022-02-16 11:50:01.274094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481aa2f89d8e'
down_revision = '5b0c39a9c121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
