"""empty message

Revision ID: 5b0c39a9c121
Revises: 0ffbfe794ed4
Create Date: 2022-02-16 11:37:19.434193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0c39a9c121'
down_revision = '0ffbfe794ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'character', ['character_id'])
    op.create_unique_constraint(None, 'planet', ['planet_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'character', type_='unique')
    # ### end Alembic commands ###
